name: CI

on:
  push:
    tags:
      - "v*" # Or trigger on tags starting with 'v' (e.g., v1.0.0)

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
        name: Checkout src repo
        with:
          path: src
          fetch-depth: 0
          ref: main
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x" # Or your desired version

      - name: Install dependencies
        run: npm install
        working-directory: src

      - name: Build
        run: npm run build
        working-directory: src

      # Checkout destination repository
      - name: Checkout dest repo
        uses: actions/checkout@v2
        with:
          path: dest
          fetch-depth: 0
          ref: gh-pages

      # Copy the built website files
      - name: Copy website built from src/public folder
        working-directory: dest
        run: |
          rm -rf *
          yes | cp -rf ../src/public/* .  # Replace '(output_folder)' with your build output dir

      # Commit and push changes
      - name: Commit website updates
        working-directory: dest
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add .
          git diff-index --quiet HEAD || git commit -m "Deploy website updates with GitHub Actions: ${GITHUB_SHA}"
          git push origin gh-pages
