name: Deploy

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout src repo
        with:
          path: src
          fetch-depth: 0
          ref: main
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm install
        working-directory: src

      - name: Build
        run: npm run build
        working-directory: src

      # Checkout destination repository
      - name: Checkout dest repo
        uses: actions/checkout@v4
        with:
          path: dest
          fetch-depth: 0
          ref: gh-pages

      # Copy the built website files
      - name: Copy website built from src/public folder
        working-directory: dest
        run: |
          rm -rf *
          cp -rf ../src/public/* .

      # Commit and push changes
      - name: Commit website updates
        working-directory: dest
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add .
          git diff-index --quiet HEAD || git commit -m "Deploy website updates with GitHub Actions: ${GITHUB_SHA}"
          git push origin gh-pages
